name: C/C++ CI

on:
  push:
    branches: [ master-0.18 ]
  pull_request:
    branches: [ master-0.18 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: depends
      run: cd depends && make

    - name: autogen
      run: ./autogen.sh

    - name: configure
      run: ./configure
    
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck
